<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Nullable>enable</Nullable>
		<PathMap>$(MSBuildProjectDirectory)=/$(SolutionName)</PathMap>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Drizzle.Lingo.Runtime\Drizzle.Lingo.Runtime.csproj" />
        <ProjectReference Include="..\Drizzle.Ported\Drizzle.Ported.csproj" />
    </ItemGroup>
</Project>
