<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
	<PathMap>$(MSBuildProjectDirectory)=/$(SolutionName)</PathMap>
    <NoWarn>IDE0028, IDE0300, IDE0301, IDE0305, IDE0290</NoWarn> <!-- Mostly collection initialization stuff -->
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Drizzle.Lingo.Runtime\Drizzle.Lingo.Runtime.csproj" />
  </ItemGroup>

</Project>
